name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.8'
          channel: 'stable'
      - run: flutter pub get
      - run: dart run.dart setup
      - run: dart run.dart build
